chore: correct docker build command in README
openequella/moodle-mod_openEQUELLA pull request #86
Opened 2022-02-04 06:21 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-02-04 12:24 UTC, ChristianMurphy approved these changes

2022-02-06 22:25 UTC, edalex-ian requested changes
Thanks @edalex-yinzi , great to keep doco up to date and correct.

Just a minor tweak, so that people familiar docker recognise the pattern. (If you're happy with it, seeing this is doco just use GitHub's 'accept suggestion' feature.)

2022-02-06 22:25 UTC, edalex-ian commented on README.md
> +docker build . -t moodle
It's customary to more so put the 'context' for a docker build command at the end:

```suggestion
docker build -t moodle .
```

2022-02-07 07:00 UTC, edalex-ian approved these changes
Thanks @edalex-yinzi

2022-02-07 07:01 UTC, merged